-- 0007_seed_fiscal_sponsors.sql
-- Seed 12 fiscal sponsor rows for CSTEM Global evaluation.
-- Extracted from deployed state on 2026-07-12.
-- Idempotent: TRUNCATEs and re-inserts.

BEGIN;

TRUNCATE TABLE public.fiscal_sponsors;

INSERT INTO public.fiscal_sponsors
  (name, website, model, admin_fee, sector_focus, minimum_project_size, application_process, geographic_scope, contact, fit_rationale, fit_tier, sort_order)
VALUES
  ('Multiplier',
   'https://multiplier.org/',
   'Model A (Comprehensive) — accelerator / employer of record',
   '9% of project revenue; 14% for government awards or international-currency reporting',
   'Environment, conservation, climate, sustainability, equity',
   'Not publicly disclosed — vetting via inquiry call',
   'Rolling: email projectinquiry@multiplier.org → intro call → formal application if a match',
   'International conservation/climate projects sponsored; higher fee tier for international-currency reporting',
   'projectinquiry@multiplier.org',
   'Strongest thematic match — dedicated environmental/conservation accelerator with track record of climate resilience and biodiversity projects, transparent fee, and application built for global-reach conservation initiatives.',
   'top', 1),

  ('Earth Island Institute',
   'https://www.earthisland.org/',
   'Model A, Direct Project',
   '10% of general income; negotiated indirect rate on federal grants; reduced above $1M/year',
   'Environment/environmental justice, conservation, wildlife, climate solutions, indigenous communities, community resilience, sustainable agriculture',
   'Not publicly disclosed',
   '"Become a Project" — unsolicited applications accepted',
   'International mission overall, but generally will NOT support projects with no US base of operations',
   'Susan Kamprath, skamprath@earthisland.org, (510) 859-9100',
   'Closest thematic mirror in the environmental/conservation space (~80 sponsored projects). Requires credible US-based operations presence to qualify — CSTEM Global would need a US director/office.',
   'top', 2),

  ('New Venture Fund (NVF)',
   'https://newventurefund.org/',
   'Model A / traditional comprehensive fiscal sponsorship',
   'Not publicly disclosed ("low flat or percentage-based fee")',
   'Civil rights, climate and environment, journalism, voting/democracy, education/youth, global health and development',
   'Not publicly disclosed',
   'Applicants identify potential funders → apply via online portal → advisory board assigned if approved',
   'Operates across nine global regions',
   'newprojects@newventurefund.org, (202) 595-1061',
   'Large, credible, multi-sector sponsor with explicit climate/environment and global health & development portfolio, and proven global incubation experience (e.g. Malala Fund).',
   'top', 3),

  ('Panorama Global',
   'https://panoramaglobal.org/fiscal-sponsorship',
   'Model A (Direct Project) and Model C (Pre-Approved Grant Relationship)',
   'Model A ~10-12%; Model C ~5-7%; government/public funding ~15%',
   'Environment/sustainable growth, international development, economic development, disaster relief, health, food insecurity',
   'Not publicly disclosed — fees tailored after needs assessment',
   'Fiscal Sponsorship Inquiry intake form',
   'Explicit international development focus; offers international staffing solutions',
   'Fiscal Sponsorship Inquiry form; +1 206.420.2518; HQ Seattle, WA',
   'Explicit "international development" and "environment/sustainable growth" categories plus stated international staffing capability — well-suited to Ghana/West Africa program design.',
   'strong', 4),

  ('Empowers Africa',
   'https://empowersafrica.org/',
   'Pass-through / Model C-style for vetted African partners',
   'Not publicly disclosed',
   'Conservation, wildlife protection, community and environmental education across Africa',
   'Not publicly disclosed',
   'Curated partnership (not open rolling application); ~40+ named African partners',
   'Africa only',
   'info@empowersafrica.org, (917) 328-1611',
   'Africa-only fiscal sponsor with direct conservation and community-livelihood experience — extremely close mission overlap. Current portfolio is mostly Southern/East Africa wildlife-tourism-linked NGOs rather than West Africa.',
   'strong', 5),

  ('Give to Africa',
   'https://2africa.org/',
   'Model A (Direct Project), Model B (Independent Contractor), Model F (Technical Assistance)',
   '$1,000 admin charge cited in directory; no percentage schedule published',
   'Education, environmental protection, economic empowerment, community development across Africa',
   'Designed for "established African organizations with a strong operational foundation"',
   'Applications accepted once a year, opens every November',
   'Africa only',
   'victoria.philips@2africa.org',
   'Purpose-built for African-led nonprofits across environment, education, and community development. Very young (501(c)(3) in 2025) — do diligence on operational maturity.',
   'strong', 6),

  ('Tides Center / Tides Foundation',
   'https://www.tides.org/what-we-do/fiscal-sponsorship/',
   'Model A (Comprehensive) and Model C (Single Entity Funds)',
   '9% of annual revenue standard; 15% for government funding; reduced above $1M',
   'Social/racial/environmental justice and equity-focused nonprofits',
   '~$100k annual budget; $4k operating reserve; at least one full-time employee',
   'Rolling review; two-year minimum commitment',
   'Explicitly requires a US base of operations and cannot employ staff outside the US/territories',
   'Fiscally Sponsored Project Application at tides.org',
   'Strong brand/infrastructure, but the no-overseas-staff rule limits usefulness unless all staff are US-based and Ghana operations run through local partners/consultants.',
   'consider', 7),

  ('Community Initiatives',
   'https://communityinitiatives.org/',
   'Model A',
   '10% gross receipts (non-government); 15% for government funds',
   'Broad multi-sector (children/youth notable; environment not called out)',
   '$50,000 minimum annual fundraising ($5,000 minimum admin fee)',
   'Quarterly approval cycle; enrollment within one year of acceptance',
   'Not stated as internationally focused',
   'Application details at communityinitiatives.org/learn/application-process',
   'Transparent Bay Area sponsor with clear published fees, but no explicit environmental or Africa/international specialization.',
   'consider', 8),

  ('Third Sector New England (TSNE)',
   'https://tsne.org/',
   'Model A (full fund responsibility)',
   '14% of expenditures year one; reassessed after year one but not below 10%; plus fringe rate',
   'Broad multi-sector; faith-based projects accepted with conditions',
   'Committed funding, 2-3 months operating reserves, 24-month budget, staff/board point person',
   'Rolling admissions; minimum 9 weeks to accept/decline',
   'Registered in 35+ US states; no explicit international support confirmed',
   'info@tsne.org',
   'Large, experienced generalist sponsor, but lacks environmental/international specialization; 14% first-year fee is on the higher end.',
   'consider', 9),

  ('FJC — A Foundation of Philanthropic Funds',
   'https://fjc.org/fiscal-sponsorship-program',
   'Low-cost administrative/pass-through sponsorship (accounts, grants, compliance)',
   '1% admin fee on avg daily balance; 4%+ transaction fee on incoming funds; no minimum balance',
   'Education, health services, religion, science, arts and culture, environment',
   'No minimum balance',
   'Submit overview, 2-year budget, staff/board summary → Fiscal Sponsorship Committee review → FSP Agreement',
   'No geographic limitations — organizations from 40+ countries have participated',
   'Allison van Hee, vanhee@fjc.org, (917) 534-7241',
   'Very low-cost pass-through option with explicit no-geographic-limits stance. Best if CSTEM Global wants light-touch admin infrastructure rather than a full accelerator.',
   'consider', 10),

  ('Rockefeller Philanthropy Advisors (RPA)',
   'https://www.rockpa.org/',
   'Comprehensive/Model A-style (label not explicit on site)',
   'Not publicly disclosed',
   'Sponsors 100+ projects; emphasizes funder collaboratives and cross-sector partnerships',
   'Not publicly disclosed',
   'Relationship-first (typically referrals / major donor introductions)',
   'Globally oriented',
   'General inquiries via rockpa.org',
   'High-prestige, donor-network-oriented — higher barrier to entry for an early-stage org without an existing RPA relationship. Worth a conversation if CSTEM Global secures a major institutional backer.',
   'consider', 11),

  ('Rainforest Trust',
   'https://www.rainforesttrust.org/',
   'NOT a fiscal sponsor',
   'N/A',
   'Rainforest/habitat conservation via land protection grants',
   'N/A',
   'N/A — no fiscal sponsorship application',
   'International grants to in-country partners',
   'N/A',
   'Investigated and ruled out — Rainforest Trust is a grantmaking conservation organization, not a fiscal-sponsorship host. Kept here for transparency; consider as a future funder, not a sponsor.',
   'excluded', 99);

COMMIT;
